name: fakng_mobile
description: faang vacancies
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.2.0
  dio: ^4.0.6
  freezed_annotation: ^2.1.0
  animated_theme_switcher: ^2.0.6
  go_router: ^4.2.7
  logger: ^1.1.0
  json_annotation: ^4.6.0
  flutter_bloc: ^8.1.1
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.6+1
  url_launcher: ^6.1.5
  cupertino_back_gesture: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

# flutter_icons:
#    android: "launcher_icon"
#    ios: true
#    image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
      - assets/translations/
      - assets/images/
      - assets/icons/
  fonts:
      - family: Inter
        fonts:
            - asset: assets/fonts/inter/Inter-ExtraLight.ttf
              weight: 200
            - asset: assets/fonts/inter/Inter-Light.ttf
              weight: 300
            - asset: assets/fonts/inter/Inter-Regular.ttf
              weight: 400
            - asset: assets/fonts/inter/Inter-Medium.ttf
              weight: 500
            - asset: assets/fonts/inter/Inter-SemiBold.ttf
              weight: 600
            - asset: assets/fonts/inter/Inter-Bold.ttf
              weight: 700
            - asset: assets/fonts/inter/Inter-ExtraBold.ttf
              weight: 800


